### ISSUE TITLE
[Feature Request] - Remove Jquery Dependency

### ISSUE THREAD

**Issue by katriellucas** [gabrielfins/ripple-effect#5]
Nice project, but I believe it's worth removing jquery if it's not super hard, it will greatly decrease the overall size of your lib. Most jquery functions have javascript equivalent nowdays. Good luck.

**Comment by henriquek3** [comment]
up

**Comment by BanDroid** [comment]
my internet is a*ss right now, anyone could help me to check my PR, run index.html and see if it's working as you wish or not

**Comment by gabrielfins** [comment]
completed by #8. thanks @BanDroid
