### ISSUE TITLE
[Suggestion] - (pt-br) add button to copy the code on documentation webiste

### ISSUE THREAD

**Issue by Brendon3578** [gabrielfins/ripple-effect#6]
Olá, o projeto que você fez é muito útil e fácil de ser usado.

Uma sugestão para a página que você fez pra demonstrar o projeto é adicionar um botão de copiar o código nos code block que você fez no site. Exemplo de codeblock que você criou no website:

```
npm install @gabrielfins/ripple-effect
```

**Comment by gabrielfins** [comment]
Feito! 👍
